# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mkdocs.exceptions as module_0


def test_case_0():
    str_0 = "'qw|jl2+IgC5f7"
    build_error_0 = module_0.BuildError(str_0)


def test_case_1():
    str_0 = "Jq:zwP(E5S0bdOo|JF"
    str_1 = "URL or local path of the registry file that declares all known MkDocs-related projects."
    configuration_error_0 = module_0.ConfigurationError(str_1)
    abort_0 = module_0.Abort(str_0)
    assert module_0.Abort.code == 1
    str_2 = abort_0.format_message()
    str_3 = abort_0.__str__()
    none_type_0 = abort_0.show()
