# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mkdocs.utils.templates as module_0


def test_case_0():
    template_context_0 = module_0.TemplateContext()


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ""
    module_0.script_tag_filter(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    template_context_0 = module_0.TemplateContext()
    module_0.script_tag_filter(template_context_0, template_context_0)
