# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mkdocs.utils.rendering as module_0
import xml.etree.ElementTree as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    none_type_0 = None
    module_0.get_heading_text(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "f"
    module_0.get_heading_text(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = ""
    module_0.get_heading_text(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    var_0 = module_1.ProcessingInstruction(none_type_0)
    module_0.get_heading_text(var_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    tuple_0 = ()
    var_0 = module_1.Comment(tuple_0)
    tuple_1 = (var_0,)
    module_0.get_heading_text(tuple_1, tuple_0)
