# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mkdocs.utils.meta as module_0


def test_case_0():
    str_0 = "Qd4\n40*#79FNx"
    tuple_0 = module_0.get_data(str_0)


def test_case_1():
    str_0 = ""
    tuple_0 = module_0.get_data(str_0)


def test_case_2():
    str_0 = "7BC:N%,&"
    tuple_0 = module_0.get_data(str_0)


def test_case_3():
    str_0 = "\t>5he,Iwe"
    tuple_0 = module_0.get_data(str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = 'ENad"w_K+=H$;tshGa\\*'
    str_1 = "\n    Type Config Option.\n\n    Validate the type of a config option against a given Python type.\n    "
    tuple_0 = module_0.get_data(str_0)
    str_2 = "\t68*"
    tuple_1 = module_0.get_data(str_1)
    tuple_2 = module_0.get_data(str_2)
    str_3 = "!\n*xaO:$cW3C"
    tuple_3 = module_0.get_data(str_2)
    str_4 = "C3:l"
    tuple_4 = module_0.get_data(str_4)
    tuple_5 = module_0.get_data(str_4)
    str_5 = "k5SXt0yp:x7\n4'N|C["
    tuple_6 = module_0.get_data(str_5)
    none_type_0 = None
    tuple_7 = module_0.get_data(str_3)
    module_0.get_data(none_type_0)
