# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mkdocs.commands.build as module_0


def test_case_0():
    str_0 = "--short"
    bool_0 = module_0.site_directory_contains_stale_files(str_0)
    assert bool_0 is False


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "Wshort"
    module_0.get_context(str_0, str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.get_context(none_type_0, none_type_0, none_type_0)


def test_case_3():
    str_0 = "o"
    bool_0 = module_0.site_directory_contains_stale_files(str_0)
    assert bool_0 is False
