# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import mkdocs.localization as module_0


def test_case_0():
    int_0 = 11
    module_0.parse_locale(int_0)


def test_case_1():
    int_0 = -2145
    module_0.install_translations(int_0, int_0, int_0)


def test_case_2():
    none_type_0 = None
    module_0.NoBabelExtension(none_type_0)
