# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mkdocs.commands.serve as module_0


@pytest.mark.xfail(strict=True)
@pytest.mark.skip(reason='Does not terminate')
def test_case_0():
    module_0.serve()
