# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mkdocs.utils.cache as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "main.html"
    module_0.download_url(str_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "r{vj{_xfnCyJ>"
    module_0.download_and_cache_url(str_0, str_0)
