# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import mkdocs.commands.new as module_0


def test_case_0():
    str_0 = ""
    none_type_0 = module_0.new(str_0)
    assert module_0.config_text == "site_name: My Docs\n"
    assert (
        module_0.index_text
        == "# Welcome to MkDocs\n\nFor full documentation visit [mkdocs.org](https://www.mkdocs.org).\n\n## Commands\n\n* `mkdocs new [dir-name]` - Create a new project.\n* `mkdocs serve` - Start the live-reloading docs server.\n* `mkdocs build` - Build the documentation site.\n* `mkdocs -h` - Print help message and exit.\n\n## Project layout\n\n    mkdocs.yml    # The configuration file.\n    docs/\n        index.md  # The documentation homepage.\n        ...       # Other markdown pages, images and other files.\n"
    )


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "\x0c89/}jsN"
    module_0.new(str_0)


def test_case_2():
    str_0 = 'i}wgW`"GgllVp'
    none_type_0 = module_0.new(str_0)
    assert module_0.config_text == "site_name: My Docs\n"
    assert (
        module_0.index_text
        == "# Welcome to MkDocs\n\nFor full documentation visit [mkdocs.org](https://www.mkdocs.org).\n\n## Commands\n\n* `mkdocs new [dir-name]` - Create a new project.\n* `mkdocs serve` - Start the live-reloading docs server.\n* `mkdocs build` - Build the documentation site.\n* `mkdocs -h` - Print help message and exit.\n\n## Project layout\n\n    mkdocs.yml    # The configuration file.\n    docs/\n        index.md  # The documentation homepage.\n        ...       # Other markdown pages, images and other files.\n"
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "&[?<7vAYw\x0b"
    none_type_0 = module_0.new(str_0)
    assert module_0.config_text == "site_name: My Docs\n"
    assert (
        module_0.index_text
        == "# Welcome to MkDocs\n\nFor full documentation visit [mkdocs.org](https://www.mkdocs.org).\n\n## Commands\n\n* `mkdocs new [dir-name]` - Create a new project.\n* `mkdocs serve` - Start the live-reloading docs server.\n* `mkdocs build` - Build the documentation site.\n* `mkdocs -h` - Print help message and exit.\n\n## Project layout\n\n    mkdocs.yml    # The configuration file.\n    docs/\n        index.md  # The documentation homepage.\n        ...       # Other markdown pages, images and other files.\n"
    )
    str_1 = ".git"
    none_type_1 = module_0.new(str_1)
    module_0.new(none_type_1)
